### ISSUE TITLE
Todo Items

### ISSUE THREAD

**Issue by coolacid** [coolacid/nodecg-progress#1]
- [x] If nucleus doesn't exist, use base events
- [ ] Track followers using bubu (Waiting for PR)
- [ ] Tip Text needs <3 if longer
